### ISSUE TITLE
Thread pool control without Akka

### ISSUE THREAD

**Issue by esroush** [zalando-incubator/nakadi-klients#19]
Previous version of NakadiClient allowed management of its thread pool in a java/spring-friendly way. The only configuration possible in the present version is via Akka configuration files, which is an undesirable dependency for applications that merely want to use the NakadiClient.

**Comment by akauppi** [comment]
Hi @esroush 
I'm coming to the project from the Scala background. I could see one structural problem arising - what exactly is the intended focus of the project? Scala, Java, or both? Currently it's a mix.

Architecturally, I'd like there to be a clear underneath core part, and a primary end user target. Any other adaptations can then be done (and tested) separately.

Do you know if there's currently a decision about such target focus? (i.e. can we go with Akka until ready, and collect any Java specific issues until that time)?

**Comment by esroush** [comment]
@akauppi I think there has been no stated focus in terms of Java or Scala. Rather, my understanding is that the underlying technology was changed in the most recent rewrite for development reasons.
