### ISSUE TITLE
Java Client for Nakadi JVM M1

### ISSUE THREAD

**Issue by tmuehl** [zalando-incubator/nakadi-klients#22]
**As a** Nakadi customer
**I want to** have a Java Client for the interface implemented in the Nakadi JVM Version in Milestone 1
**Such that** I don't need to reinvent the wheel and can start faster.

**Comment by codechimp** [comment]
Would the ARUHA team support the implementation as we did for the last version (Scala backend with Java interface)?

**Comment by tmuehl** [comment]
Definitely! :)
At least me, I also plan to contribute. Already wanted to start, but something came in between.
