### ISSUE TITLE
Use abstraction of the SLF4J log library

### ISSUE THREAD

**Issue by danielrohe** [zalando-incubator/nakadi-klients#82]
Please only include the slf4j-api as a dependency and let the client choose the used slf4j binding (logback, log4j, ...).

**Comment by kanuku** [comment]
@danielrohe 
Which version of the client?
This should be already the case: See #79. since pre-alpha.16.

**Comment by danielrohe** [comment]
In pre-alpha.16 there is still a dependency to logback and not to slf4j-api 

    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.1.7</version>
      <scope>runtime</scope>
    </dependency>

for the client. I would expect that only slf4j-api is there and the application that integrates this provides e.g. logback or log4j as backend for slf4j. Currently I had to exclude logback-classic in our application because we use log4j as slf4j backend.

**Comment by kanuku** [comment]
Issues is being reopend because, logback needs to be used as test dependency only...
Right now it still needs to be excluded from the project.

**Comment by kanuku** [comment]
Fixed with 519c0e5!
